import { makeTheme } from "./themes.mjs";
import type { AccentColor, Mode } from "./types.mjs";
import { hex } from "./utilities.mjs";

export const generateTerminal = (mode: Mode) => {
    const generatedTerminal = {
        name: `Flexoki ${mode}`,
        ...hex(makeTheme(mode, "Blue").mapping.terminal),
    };

    return JSON.stringify(generatedTerminal, Object.keys(generatedTerminal).sort(), 4);
};

export const generateTheme = (mode: Mode, accentColor: AccentColor) => {
    const createdTheme = makeTheme(mode, accentColor);
    const { baseTones, syntax, terminal, ui, theme } = {
        baseTones: hex(createdTheme.mapping.baseTones),
        syntax: hex(createdTheme.mapping.syntax),
        terminal: hex(createdTheme.mapping.terminal),
        ui: hex(createdTheme.mapping.ui),
        theme: hex(createdTheme.theme),
    };
    const test = "#FF00FF";

    const generatedTheme = {
        $schema: "vscode://schemas/color-theme",
        name: `Flexoki ${mode} ${accentColor}`,
        colors: {
            "activityBar.activeBackground": theme.ui,
            "activityBar.activeBorder": ui.accent,
            "activityBar.activeFocusBorder": ui.accent,
            "activityBar.background": theme.ui,
            "activityBar.border": ui.borders,
            "activityBar.dropBorder": ui.accent,
            "activityBar.foreground": ui.accent,
            "activityBar.inactiveForeground": ui.primary_text,
            "activityBarBadge.background": ui.accent,
            "activityBarBadge.foreground": baseTones.paper,
            "activityBarTop.activeBackground": theme.ui,
            "activityBarTop.activeBorder": ui.accent,
            "activityBarTop.background": theme.ui,
            "activityBarTop.dropBorder": ui.accent,
            "activityBarTop.foreground": ui.accent,
            "activityBarTop.inactiveForeground": ui.primary_text,
            "badge.background": ui.accent,
            "badge.foreground": baseTones.paper,
            "banner.background": theme.ui,
            "banner.foreground": ui.primary_text,
            "banner.iconForeground": ui.primary_text,
            "breadcrumb.activeSelectionForeground": ui.accent,
            "breadcrumb.background": ui.main_background,
            "breadcrumb.focusForeground": ui.primary_text,
            "breadcrumb.foreground": ui.muted_text,
            "breadcrumbPicker.background": ui.main_background,
            "button.background": theme.ui,
            "button.border": theme.ui3,
            "button.foreground": ui.primary_text,
            "button.hoverBackground": theme.ui2,
            "button.secondaryBackground": theme.ui,
            "button.secondaryForeground": ui.primary_text,
            "button.secondaryHoverBackground": theme.ui2,
            "button.separator": theme.ui3,
            "checkbox.background": theme.ui,
            "checkbox.border": theme.ui3,
            "checkbox.foreground": ui.primary_text,
            "checkbox.selectBackground": ui.accent,
            "checkbox.selectBorder": ui.accent,
            "commandCenter.activeBackground": theme.ui2,
            "commandCenter.activeBorder": theme.ui3,
            "commandCenter.activeForeground": ui.primary_text,
            "commandCenter.background": theme.ui,
            "commandCenter.border": theme.ui3,
            "commandCenter.debuggingBackground": ui.transparent_bg_active,
            "commandCenter.foreground": ui.muted_text,
            "commandCenter.inactiveBorder": theme.ui3,
            "commandCenter.inactiveForeground": ui.faint_text,
            "debugConsole.errorForeground": ui.error_text,
            "debugConsole.infoForeground": ui.primary_text,
            "debugConsole.sourceForeground": ui.primary_text,
            "debugConsole.warningForeground": ui.warning_text,
            "debugConsoleInputIcon.foreground": ui.primary_text,
            "dropdown.background": ui.secondary_background,
            "dropdown.border": ui.active_borders,
            "dropdown.foreground": ui.primary_text,
            "dropdown.listBackground": ui.secondary_background,
            "editor.background": ui.main_background,
            "editorBracketHighlight.foreground1": theme.or,
            "editorBracketHighlight.foreground2": theme.ye,
            "editorBracketHighlight.foreground3": theme.cy,
            "editorBracketHighlight.foreground4": theme.bl,
            "editorBracketHighlight.foreground5": theme.pu,
            "editorBracketHighlight.foreground6": theme.ma,
            "editorBracketHighlight.unexpectedBracket.foreground": ui.error_text,
            "editorBracketMatch.background": ui.transparent,
            "editorBracketMatch.border": ui.accent,
            "editorBracketPairGuide.activeBackground1": theme.or,
            "editorBracketPairGuide.activeBackground2": theme.ye,
            "editorBracketPairGuide.activeBackground3": theme.cy,
            "editorBracketPairGuide.activeBackground4": theme.bl,
            "editorBracketPairGuide.activeBackground5": theme.pu,
            "editorBracketPairGuide.activeBackground6": theme.ma,
            "editorBracketPairGuide.background1": theme.or,
            "editorBracketPairGuide.background2": theme.ye,
            "editorBracketPairGuide.background3": theme.cy,
            "editorBracketPairGuide.background4": theme.bl,
            "editorBracketPairGuide.background5": theme.pu,
            "editorBracketPairGuide.background6": theme.ma,
            "editorCursor.background": ui.main_background,
            "editorCursor.foreground": ui.primary_text,
            "editorGroup.border": ui.borders,
            "editorGroup.dropBackground": ui.transparent_bg_hover,
            "editorGroupHeader.border": ui.borders,
            "editorGroupHeader.tabsBackground": theme.ui,
            "editorGroupHeader.tabsBorder": ui.borders,
            "editorHoverWidget.background": theme.ui,
            "editorHoverWidget.border": ui.borders,
            "editorHoverWidget.foreground": ui.primary_text,
            "editorHoverWidget.highlightForeground": ui.primary_text,
            "editorHoverWidget.statusBarBackground": theme.ui2,
            "editorInlayHint.background": ui.transparent_bg,
            "editorInlayHint.foreground": ui.muted_text,
            "editorInlayHint.parameterBackground": ui.transparent_bg,
            "editorInlayHint.parameterForeground": ui.muted_text,
            "editorInlayHint.typeBackground": ui.transparent_bg,
            "editorInlayHint.typeForeground": ui.muted_text,
            "editorLineNumber.activeForeground": ui.primary_text,
            "editorLineNumber.dimmedForeground": ui.faint_text,
            "editorLineNumber.foreground": ui.muted_text,
            "editorStickyScroll.background": ui.main_background,
            "editorStickyScroll.border": ui.borders,
            "editorStickyScroll.shadow": ui.shadow,
            "editorStickyScrollHover.background": ui.transparent,
            "editorWidget.background": theme.ui,
            "editorWidget.border": ui.borders,
            "editorWidget.foreground": ui.primary_text,
            "editorWidget.resizeBorder": ui.borders,
            "extensionBadge.remoteBackground": ui.accent,
            "extensionBadge.remoteForeground": baseTones.paper,
            "extensionButton.background": theme.ui,
            "extensionButton.foreground": ui.primary_text,
            "extensionButton.hoverBackground": theme.ui2,
            "extensionButton.prominentBackground": theme.ui,
            "extensionButton.prominentForeground": ui.primary_text,
            "extensionButton.prominentHoverBackground": theme.ui2,
            "extensionButton.separator": theme.ui3,
            "extensionIcon.preReleaseForeground": theme.gr,
            "extensionIcon.sponsorForeground": theme.ma,
            "extensionIcon.starForeground": theme.or,
            "extensionIcon.verifiedForeground": theme.bl,
            "focusBorder": ui.accent,
            "foreground": ui.primary_text,
            "gitDecoration.addedResourceForeground": theme.gr,
            "gitDecoration.conflictingResourceForeground": theme.ma,
            "gitDecoration.deletedResourceForeground": theme.re,
            "gitDecoration.ignoredResourceForeground": ui.muted_text,
            "gitDecoration.modifiedResourceForeground": theme.ye,
            "gitDecoration.renamedResourceForeground": theme.gr,
            "gitDecoration.stageDeletedResourceForeground": theme.re,
            "gitDecoration.stageModifiedResourceForeground": theme.ye,
            "gitDecoration.submoduleResourceForeground": theme.bl,
            "gitDecoration.untrackedResourceForeground": theme.gr,
            "icon.foreground": ui.muted_text,
            "input.background": ui.secondary_background,
            "input.border": ui.active_borders,
            "input.foreground": ui.primary_text,
            "input.placeholderForeground": ui.faint_text,
            "keybindingLabel.background": ui.secondary_background,
            "keybindingLabel.border": ui.borders,
            "keybindingLabel.bottomBorder": ui.borders,
            "keybindingLabel.foreground": ui.accent,
            "keybindingTable.headerBackground": ui.secondary_background,
            "keybindingTable.rowsBackground": ui.secondary_background,
            "list.activeSelectionBackground": ui.transparent_bg_hover,
            "list.activeSelectionForeground": ui.primary_text,
            "list.activeSelectionIconForeground": ui.primary_text,
            "list.deemphasizedForeground": ui.muted_text,
            "list.dropBackground": ui.transparent_bg_hover,
            "list.dropBetweenBackground": ui.transparent_bg_hover,
            "list.errorForeground": ui.error_text,
            "list.filterMatchBackground": ui.accent,
            "list.filterMatchBorder": ui.transparent,
            "list.focusAndSelectionOutline": ui.accent,
            "list.focusBackground": ui.transparent_bg_hover,
            "list.focusForeground": ui.primary_text,
            "list.focusHighlightForeground": ui.primary_text,
            "list.focusOutline": ui.transparent,
            "list.highlightForeground": ui.primary_text,
            "list.hoverBackground": ui.transparent_bg_hover,
            "list.hoverForeground": ui.primary_text,
            "list.inactiveFocusBackground": ui.transparent_bg_hover,
            "list.inactiveFocusOutline": ui.transparent,
            "list.inactiveSelectionBackground": ui.transparent_bg,
            "list.inactiveSelectionForeground": ui.primary_text,
            "list.inactiveSelectionIconForeground": ui.primary_text,
            "list.invalidItemForeground": ui.error_text,
            "list.warningForeground": ui.warning_text,
            "listFilterWidget.background": theme.ui,
            "listFilterWidget.noMatchesOutline": ui.transparent,
            "listFilterWidget.outline": ui.borders,
            "listFilterWidget.shadow": ui.shadow,
            "menu.background": ui.main_background,
            "menu.border": ui.borders,
            "menu.foreground": ui.primary_text,
            "menu.selectionBackground": theme.ui2,
            "menu.selectionBorder": ui.transparent,
            "menu.selectionForeground": ui.primary_text,
            "menu.separatorBackground": ui.borders,
            "menubar.selectionBackground": theme.ui2,
            "menubar.selectionBorder": ui.transparent,
            "menubar.selectionForeground": ui.primary_text,
            "minimap.background": ui.transparent,
            "minimapSlider.activeBackground": ui.transparent_bg_active,
            "minimapSlider.background": ui.transparent_bg,
            "minimapSlider.hoverBackground": ui.transparent_bg_hover,
            "panel.background": ui.secondary_background,
            "panel.border": ui.borders,
            "panel.dropBorder": ui.accent,
            "panelInput.border": ui.active_borders,
            "panelSection.border": ui.borders,
            "panelSection.dropBackground": ui.transparent_bg_hover,
            "panelSectionHeader.background": ui.main_background,
            "panelSectionHeader.border": ui.borders,
            "panelSectionHeader.foreground": ui.primary_text,
            "panelStickyScroll.background": ui.main_background,
            "panelStickyScroll.border": ui.borders,
            "panelStickyScroll.shadow": ui.shadow,
            "panelTitle.activeBorder": ui.accent,
            "panelTitle.activeForeground": ui.primary_text,
            "panelTitle.inactiveForeground": ui.muted_text,
            "quickInput.background": ui.main_background,
            "quickInput.foreground": ui.primary_text,
            "quickInputList.focusBackground": theme.ui2,
            "quickInputList.focusForeground": ui.primary_text,
            "quickInputList.focusIconForeground": ui.primary_text,
            "quickInputTitle.background": test,
            "scrollbar.shadow": ui.shadow,
            "scrollbarSlider.activeBackground": ui.transparent_bg_active,
            "scrollbarSlider.background": ui.transparent_bg,
            "scrollbarSlider.hoverBackground": ui.transparent_bg_hover,
            "sideBar.background": ui.secondary_background,
            "sideBar.border": ui.borders,
            "sideBar.dropBackground": ui.transparent_bg_hover,
            "sideBar.foreground": ui.primary_text,
            "sideBarSectionHeader.background": theme.ui,
            "sideBarSectionHeader.border": ui.borders,
            "sideBarSectionHeader.foreground": ui.primary_text,
            "sideBarTitle.foreground": ui.primary_text,
            "statusBar.background": ui.secondary_background,
            "statusBar.border": ui.borders,
            "statusBar.debuggingBackground": ui.accent,
            "statusBar.debuggingForeground": baseTones.paper,
            "statusBar.focusBorder": ui.accent,
            "statusBar.foreground": ui.primary_text,
            "statusBar.noFolderBackground": ui.secondary_background,
            "tab.activeBackground": ui.main_background,
            "tab.activeBorder": theme.ui2,
            "tab.activeBorderTop": ui.accent,
            "tab.activeForeground": ui.primary_text,
            "tab.border": theme.ui2,
            "tab.hoverBackground": ui.main_background,
            "tab.hoverBorder": ui.transparent,
            "tab.hoverForeground": ui.primary_text,
            "tab.inactiveBackground": ui.transparent,
            "tab.inactiveForeground": ui.muted_text,
            "tab.lastPinnedBorder": test,
            "tab.selectedBackground": ui.main_background,
            "tab.selectedBorderTop": ui.transparent,
            "tab.selectedForeground": ui.muted_text,
            "tab.unfocusedActiveBorder": ui.transparent,
            "tab.unfocusedActiveBorderTop": ui.transparent,
            "tab.unfocusedHoverBackground": ui.main_background,
            "tab.unfocusedHoverBorder": ui.hovered_borders,
            "tab.unfocusedHoverForeground": ui.primary_text,
            "terminal.ansiBlack": terminal.black,
            "terminal.ansiBlue": terminal.blue,
            "terminal.ansiBrightBlack": terminal.brightBlack,
            "terminal.ansiBrightBlue": terminal.brightBlue,
            "terminal.ansiBrightCyan": terminal.brightCyan,
            "terminal.ansiBrightGreen": terminal.brightGreen,
            "terminal.ansiBrightMagenta": terminal.brightPurple,
            "terminal.ansiBrightRed": terminal.brightRed,
            "terminal.ansiBrightWhite": terminal.brightWhite,
            "terminal.ansiBrightYellow": terminal.brightYellow,
            "terminal.ansiCyan": terminal.cyan,
            "terminal.ansiGreen": terminal.green,
            "terminal.ansiMagenta": terminal.purple,
            "terminal.ansiRed": terminal.red,
            "terminal.ansiWhite": terminal.white,
            "terminal.ansiYellow": terminal.yellow,
            "terminal.background": ui.secondary_background,
            "terminal.border": ui.borders,
            "terminal.dropBackground": ui.transparent_bg_hover,
            "terminal.foreground": terminal.foreground,
            "terminal.inactiveSelectionBackground": ui.hovered_borders,
            "terminal.selectionBackground": terminal.selectionBackground,
            "terminal.tab.activeBorder": ui.accent,
            "terminalCursor.background": terminal.background,
            "terminalCursor.foreground": terminal.foreground,
            "titleBar.activeBackground": theme.ui,
            "titleBar.activeForeground": ui.primary_text,
            "titleBar.border": ui.borders,
            "titleBar.inactiveBackground": theme.ui,
            "titleBar.inactiveForeground": ui.muted_text,
            "welcomePage.background": ui.main_background,
            "welcomePage.progress.background": theme.ui,
            "welcomePage.progress.foreground": theme.ui3,
            "welcomePage.tileBackground": theme.ui,
            "welcomePage.tileBorder": ui.borders,
            "welcomePage.tileHoverBackground": theme.ui2,
            "widget.border": ui.borders,
            "widget.shadow": ui.shadow,
        },
        // tokenColors: dark ? darkTokens() : lightTokens(),
        tokenColors: [
            { scope: ["emphasis"], settings: { fontStyle: "italic" } },
            { scope: ["strong"], settings: { fontStyle: "bold" } },
            { scope: ["header", "markup.heading"], settings: { foreground: theme.bl } },
            { scope: ["comment"], settings: { foreground: syntax.comments } },
            {
                scope: ["token.info-token"],
                settings: {
                    foreground: theme.bl,
                },
            },
            {
                scope: ["token.warn-token"],
                settings: {
                    foreground: ui.warning_text,
                },
            },
            {
                scope: ["token.error-token"],
                settings: {
                    foreground: ui.error_text,
                },
            },
            {
                scope: ["token.debug-token"],
                settings: {
                    foreground: theme.pu,
                },
            },
            {
                scope: ["entity.name.function"],
                settings: {
                    foreground: syntax.functions,
                },
            },
            {
                scope: ["keyword", "entity.name.keyword"],
                settings: {
                    foreground: syntax.keywords,
                },
            },
            {
                scope: ["entity.name.type", "storage.type", "support.type"],
                settings: {
                    foreground: theme.pu,
                },
            },
            {
                scope: ["storage.modifier"],
                settings: {
                    foreground: theme.pu,
                },
            },
            {
                scope: ["string"],
                settings: {
                    foreground: syntax.strings,
                },
            },
            {
                scope: ["meta.object"],
                settings: {
                    foreground: syntax.constants,
                },
            },
            {
                scope: ["meta.block.namespace"],
                settings: {
                    foreground: syntax.keywords,
                },
            },
            {
                scope: ["punctuation"],
                settings: {
                    foreground: syntax.punctuation,
                },
            },
            {
                scope: ["variable"],
                settings: {
                    foreground: syntax.variables,
                },
            },
            {
                scope: ["constant"],
                settings: {
                    foreground: syntax.constants,
                },
            },
            {
                scope: ["constant.numeric"],
                settings: {
                    foreground: syntax.numbers,
                },
            },
            {
                scope: ["constant.character"],
                settings: {
                    foreground: syntax.strings,
                },
            },
            {
                scope: ["constant.language"],
                settings: {
                    foreground: syntax.language_features,
                },
            },
            {
                scope: ["invalid"],
                settings: {
                    foreground: syntax.invalid,
                },
            },
        ],
        semanticHighlighting: true,
        semanticTokenColors: {
            newOperator: syntax.operators,
            stringLiteral: syntax.strings,
            customLiteral: syntax.strings,
            numberLiteral: syntax.numbers,
            namespace: syntax.punctuation,
            type: theme.pu,
        },
    };

    return JSON.stringify(generatedTheme, null, 4);
};
