import Color from "colorjs.io";

export type Theme = "Dark" | "Light";

export type AccentColor =
    | "Red"
    | "Orange"
    | "Yellow"
    | "Green"
    | "Cyan"
    | "Blue"
    | "Purple"
    | "Magenta";

export interface ColorTheme {
    [index: string]: Color | string;
    "bg": Color | string;
    "bg-2": Color | string;
    "ui": Color | string;
    "ui-2": Color | string;
    "ui-3": Color | string;
    "tx-3": Color | string;
    "tx-2": Color | string;
    "tx": Color | string;
    "re": Color | string;
    "re2": Color | string;
    "or": Color | string;
    "or2": Color | string;
    "ye": Color | string;
    "ye2": Color | string;
    "gr": Color | string;
    "gr2": Color | string;
    "cy": Color | string;
    "cy2": Color | string;
    "bl": Color | string;
    "bl2": Color | string;
    "pu": Color | string;
    "pu2": Color | string;
    "ma": Color | string;
    "ma2": Color | string;
    "transparent": Color | string;
}

export interface Mapping {
    ui: {
        [index: string]: Color | string;
        "main-background": Color | string;
        "secondary-background": Color | string;
        "borders": Color | string;
        "hovered-borders": Color | string;
        "active-borders": Color | string;
        "faint-text": Color | string;
        "muted-text": Color | string;
        "primary-text": Color | string;
        "error-text": Color | string;
        "warning-text": Color | string;
        "success-text": Color | string;
        "links": Color | string;
        "active-states": Color | string;
    };
    syntax: {
        [index: string]: Color | string;
        "comments": Color | string;
        "punctuation": Color | string;
        "operators": Color | string;
        "invalid": Color | string;
        "imports": Color | string;
        "functions": Color | string;
        "constants": Color | string;
        "keywords": Color | string;
        "strings": Color | string;
        "variables": Color | string;
        "attributes": Color | string;
        "numbers": Color | string;
        "language-features": Color | string;
    };
}

export const baseTone = {
    "black": new Color("#100F0F"),
    "base-950": new Color("#1C1B1A"),
    "base-900": new Color("#282726"),
    "base-850": new Color("#343331"),
    "base-800": new Color("#403E3C"),
    "base-700": new Color("#575653"),
    "base-600": new Color("#6F6E69"),
    "base-500": new Color("#878580"),
    "base-300": new Color("#B7B5AC"),
    "base-200": new Color("#CECDC3"),
    "base-150": new Color("#DAD8CE"),
    "base-100": new Color("#E6E4D9"),
    "base-50": new Color("#F2F0E5"),
    "paper": new Color("#FFFCF0"),
};

export const accentColor = {
    "red-600": new Color("#AF3029"),
    "orange-600": new Color("#BC5215"),
    "yellow-600": new Color("#AD8301"),
    "green-600": new Color("#66800B"),
    "cyan-600": new Color("#24837B"),
    "blue-600": new Color("#205EA6"),
    "purple-600": new Color("#5E409D"),
    "magenta-600": new Color("#A02F6F"),
    "red-400": new Color("#D14D41"),
    "orange-400": new Color("#DA702C"),
    "yellow-400": new Color("#D0A215"),
    "green-400": new Color("#879A39"),
    "cyan-400": new Color("#3AA99F"),
    "blue-400": new Color("#4385BE"),
    "purple-400": new Color("#8B7EC8"),
    "magenta-400": new Color("#CE5D97"),
};

export const dark: ColorTheme = {
    "bg": baseTone["black"],
    "bg-2": baseTone["base-950"],
    "ui": baseTone["base-900"],
    "ui-2": baseTone["base-850"],
    "ui-3": baseTone["base-800"],
    "tx-3": baseTone["base-700"],
    "tx-2": baseTone["base-500"],
    "tx": baseTone["base-200"],
    "re": accentColor["red-400"],
    "re2": accentColor["red-600"],
    "or": accentColor["orange-400"],
    "or2": accentColor["orange-600"],
    "ye": accentColor["yellow-400"],
    "ye2": accentColor["yellow-600"],
    "gr": accentColor["green-400"],
    "gr2": accentColor["green-600"],
    "cy": accentColor["cyan-400"],
    "cy2": accentColor["cyan-600"],
    "bl": accentColor["blue-400"],
    "bl2": accentColor["blue-600"],
    "pu": accentColor["purple-400"],
    "pu2": accentColor["purple-600"],
    "ma": accentColor["magenta-400"],
    "ma2": accentColor["magenta-600"],
    "transparent": new Color("#00000000"),
};

export const light: ColorTheme = {
    "bg": baseTone["paper"],
    "bg-2": baseTone["base-50"],
    "ui": baseTone["base-100"],
    "ui-2": baseTone["base-150"],
    "ui-3": baseTone["base-200"],
    "tx-3": baseTone["base-300"],
    "tx-2": baseTone["base-600"],
    "tx": baseTone["black"],
    "re": accentColor["red-600"],
    "re2": accentColor["red-400"],
    "or": accentColor["orange-600"],
    "or2": accentColor["orange-400"],
    "ye": accentColor["yellow-600"],
    "ye2": accentColor["yellow-400"],
    "gr": accentColor["green-600"],
    "gr2": accentColor["green-400"],
    "cy": accentColor["cyan-600"],
    "cy2": accentColor["cyan-400"],
    "bl": accentColor["blue-600"],
    "bl2": accentColor["blue-400"],
    "pu": accentColor["purple-600"],
    "pu2": accentColor["purple-400"],
    "ma": accentColor["magenta-600"],
    "ma2": accentColor["magenta-400"],
    "transparent": new Color("#FFFFFF00"),
};

export function hex(color: Color) {
    return color.toString({ format: "hex" });
}

export function hexTheme(colorTheme: ColorTheme) {
    Object.entries(colorTheme).forEach(([key, value]: [string, Color | string]) => {
        colorTheme[key] = hex(value as Color);
    });
    return colorTheme;
}

export function makeMapping(colorTheme: ColorTheme): Mapping {
    return {
        ui: {
            "main-background": colorTheme["bg"],
            "secondary-background": colorTheme["bg-2"],
            "borders": colorTheme["ui"],
            "hovered-borders": colorTheme["ui-2"],
            "active-borders": colorTheme["ui-3"],
            "faint-text": colorTheme["tx-3"],
            "muted-text": colorTheme["tx-2"],
            "primary-text": colorTheme["tx"],
            "error-text": colorTheme["re"],
            "warning-text": colorTheme["or"],
            "success-text": colorTheme["gr"],
            "links": colorTheme["cy"],
            "active-states": colorTheme["cy"],
        },
        syntax: {
            "comments": colorTheme["tx-3"],
            "punctuation": colorTheme["tx-2"],
            "operators": colorTheme["tx-2"],
            "invalid": colorTheme["re"],
            "imports": colorTheme["re"],
            "functions": colorTheme["or"],
            "constants": colorTheme["ye"],
            "keywords": colorTheme["gr"],
            "strings": colorTheme["cy"],
            "variables": colorTheme["bl"],
            "attributes": colorTheme["bl"],
            "numbers": colorTheme["pu"],
            "language-features": colorTheme["ma"],
        },
    };
}

export const generateTerminal = (theme: Theme) => {
    const mapping = theme === "Dark" ? makeMapping(hexTheme(dark)) : makeMapping(hexTheme(light));
    const colorTheme = theme === "Dark" ? hexTheme(dark) : hexTheme(light);

    return {
        background: mapping["ui"]["main-background"],
        black: hex(baseTone["base-950"]),
        blue: colorTheme["bl2"],
        brightBlack: hex(baseTone["base-900"]),
        brightBlue: colorTheme["bl"],
        brightCyan: colorTheme["cy"],
        brightGreen: colorTheme["gr"],
        brightPurple: colorTheme["ma"],
        brightRed: colorTheme["re"],
        brightWhite: hex(baseTone["base-50"]),
        brightYellow: colorTheme["ye"],
        cursorColor: mapping["ui"]["primary-text"],
        cyan: colorTheme["cy2"],
        foreground: mapping["ui"]["primary-text"],
        green: colorTheme["gr2"],
        name: `Flexoki ${dark ? "Dark" : "Light"}`,
        purple: colorTheme["ma2"],
        red: colorTheme["re2"],
        selectionBackground: mapping["ui"]["secondary-background"],
        white: hex(baseTone["base-100"]),
        yellow: colorTheme["ye2"],
    };
};

export const generateTheme = (theme: Theme, accentColor: AccentColor) => {
    const mapping = theme === "Dark" ? makeMapping(hexTheme(dark)) : makeMapping(hexTheme(light));
    const colorTheme = theme === "Dark" ? hexTheme(dark) : hexTheme(light);

    return {
        $schema: "vscode://schemas/color-theme",
        name: `Flexoki ${theme} ${accentColor}`,
        semanticHighlighting: true,
        colors: {
            "activityBar.activeBackground": colorTheme["transparent"],
            "activityBar.activeBorder": colorTheme["transparent"],
            "activityBar.activeFocusBorder": colorTheme["transparent"],
            "activityBar.background": dark ? mappings["ui"] : mappings["bg"],
            "activityBar.border": mappings["bg-2"],
            "activityBar.foreground": mappings["tx"],
            "activityBar.inactiveForeground": mappings["tx-3"],
            "activityBarBadge.background": mappings["bg"],
            "activityBarBadge.foreground": accent,
            "activityBarTop.activeBorder": colorTheme["transparent"],
            "activityBarTop.foreground": mappings["tx"],
            "activityBarTop.inactiveForeground": mappings["tx-2"],
            "badge.background": mappings["bg"],
            "badge.foreground": accent,
            "banner.background": dark ? mappings["ui"] : mappings["bg"],
            "banner.foreground": mappings["tx"],
            "banner.iconForeground": mappings["tx"],
            "breadcrumb.activeSelectionForeground": mappings["tx"],
            "breadcrumb.background": mappings["bg"],
            "breadcrumb.focusForeground": mappings["tx"],
            "breadcrumb.foreground": mappings["tx-2"],
            "breadcrumbPicker.background": mappings["bg"],
            "button.background": mappings["bg"],
            "button.border": mappings["ui"],
            "button.foreground": mappings["tx"],
            "button.hoverBackground": mappings["bg-2"],
            "button.secondaryBackground": mappings["bg"],
            "button.secondaryForeground": mappings["tx"],
            "button.secondaryHoverBackground": mappings["bg-2"],
            "button.separator": mappings["ui"],
            "commandCenter.activeBackground": mappings["bg"],
            "commandCenter.activeBorder": dark ? mappings["ui-2"] : mappings["ui"],
            "commandCenter.activeForeground": mappings["tx"],
            "commandCenter.background": mappings["bg-2"],
            "commandCenter.border": dark ? mappings["ui-2"] : mappings["ui"],
            "commandCenter.foreground": mappings["tx-2"],
            "commandCenter.inactiveBorder": dark ? mappings["ui-2"] : mappings["ui"],
            "commandCenter.inactiveForeground": mappings["tx-3"],
            "dropdown.background": mappings["bg"],
            "dropdown.border": mappings["ui"],
            "dropdown.foreground": mappings["tx"],
            "dropdown.listBackground": mappings["bg"],
            "editor.background": mappings["bg"],
            "editor.foreground": mappings["tx"],

            "editorActiveLineNumber.foreground": mappings["tx"],
            "editorBracketHighlight.foreground1": mappings["ye"],
            "editorBracketHighlight.foreground2": mappings["ma"],
            "editorBracketHighlight.foreground3": mappings["bl"],
            "editorBracketHighlight.foreground4": mappings["or"],
            "editorBracketHighlight.foreground5": mappings["pu"],
            "editorBracketHighlight.foreground6": mappings["gr"],
            "editorBracketHighlight.unexpectedBracket.foreground": mappings["re"],
            "editorBracketMatch.background": colorTheme["transparent"],
            "editorBracketMatch.border": mappings["tx"],

            // "editorBracketPairGuide.activeBackground1": test,
            // "editorBracketPairGuide.activeBackground2": test,
            // "editorBracketPairGuide.activeBackground3": test,
            // "editorBracketPairGuide.activeBackground4": test,
            // "editorBracketPairGuide.activeBackground5": test,
            // "editorBracketPairGuide.activeBackground6": test,
            // "editorBracketPairGuide.background1": test,
            // "editorBracketPairGuide.background2": test,
            // "editorBracketPairGuide.background3": test,
            // "editorBracketPairGuide.background4": test,
            // "editorBracketPairGuide.background5": test,
            // "editorBracketPairGuide.background6": test,

            // "editorIndentGuide.activeBackground": test,
            // "editorIndentGuide.activeBackground1": test,
            // "editorIndentGuide.activeBackground2": test,
            // "editorIndentGuide.activeBackground3": test,
            // "editorIndentGuide.activeBackground4": test,
            // "editorIndentGuide.activeBackground5": test,
            // "editorIndentGuide.activeBackground6": test,
            // "editorIndentGuide.background": test,
            // "editorIndentGuide.background1": test,
            // "editorIndentGuide.background2": test,
            // "editorIndentGuide.background3": test,
            // "editorIndentGuide.background4": test,
            // "editorIndentGuide.background5": test,
            // "editorIndentGuide.background6": test,

            "editorCursor.background": mappings["bg"],
            "editorCursor.foreground": mappings["tx"],
            "editorGroup.border": dark ? mappings["ui"] : mappings["bg-2"],
            "editorGroup.emptyBackground": mappings["bg"],
            "editorGroupHeader.border": colorTheme["transparent"],
            "editorGroupHeader.noTabsBackground": mappings["bg"],
            "editorGroupHeader.tabsBackground": mappings["ui"],
            "editorGroupHeader.tabsBorder": colorTheme["transparent"],
            "editorHoverWidget.background": mappings["bg"],
            "editorHoverWidget.border": mappings["ui"],
            "editorSuggestWidget.background": mappings["bg-2"],
            "editorWidget.background": mappings["ui"],
            "editorWidget.border": mappings["ui"],
            "editorWidget.foreground": mappings["tx"],
            "extensionBadge.remoteBackground": mappings["bg"],
            "extensionBadge.remoteForeground": accent,
            "extensionButton.background": mappings["bg-2"],
            "extensionButton.foreground": mappings["tx"],
            "extensionButton.hoverBackground": mappings["ui"],
            "extensionButton.prominentBackground": mappings["bg-2"],
            "extensionButton.prominentForeground": mappings["tx"],
            "extensionButton.prominentHoverBackground": mappings["ui"],
            "extensionButton.separator": mappings["ui-2"],
            "focusBorder": colorTheme["transparent"],
            "foreground": mappings["tx"],
            "gitDecoration.addedResourceForeground": mappings["gr"],
            "gitDecoration.conflictingResourceForeground": mappings["re"],
            "gitDecoration.deletedResourceForeground": mappings["or"],
            "gitDecoration.ignoredResourceForeground": mappings["tx-2"],
            "gitDecoration.modifiedResourceForeground": mappings["ye"],
            "gitDecoration.renamedResourceForeground": mappings["gr"],
            "gitDecoration.stageDeletedResourceForeground": mappings["or"],
            "gitDecoration.stageModifiedResourceForeground": mappings["ye"],
            "gitDecoration.submoduleResourceForeground": mappings["bl"],
            "gitDecoration.untrackedResourceForeground": mappings["gr"],
            "icon.foreground": mappings["tx-2"],
            "input.background": mappings["bg"],
            "input.border": mappings["ui"],
            "input.foreground": mappings["tx"],
            "input.placeholderForeground": mappings["tx-2"],
            "keybindingLabel.background": mappings["bg-2"],
            "keybindingLabel.border": mappings["ui"],
            "keybindingLabel.bottomBorder": mappings["ui"],
            "keybindingLabel.foreground": mappings["tx"],
            "keybindingTable.headerBackground": mappings["ui-2"],
            "keybindingTable.rowsBackground": mappings["bg-2"],
            "list.activeSelectionBackground": mappings["ui-3"],
            "list.activeSelectionForeground": mappings["tx"],
            "list.hoverBackground": mappings["ui"],
            "list.inactiveSelectionBackground": mappings["ui"],
            "list.inactiveSelectionForeground": mappings["tx"],
            "menu.background": mappings["bg"],
            "menu.border": mappings["ui"],
            "menu.foreground": mappings["tx"],
            "menu.selectionBackground": mappings["ui"],
            "menu.selectionBorder": colorTheme["transparent"],
            "menu.selectionForeground": mappings["tx"],
            "menu.separatorBackground": mappings["ui-2"],
            "menubar.selectionBackground": dark ? mappings["ui-2"] : mappings["ui"],
            "menubar.selectionBorder": colorTheme["transparent"],
            "menubar.selectionForeground": mappings["tx"],
            "panel.background": mappings["bg"],
            "panel.border": dark ? mappings["ui"] : mappings["bg-2"],
            "panelInput.border": mappings["ui"],
            "pickerGroup.border": mappings["ui"],
            "pickerGroup.foreground": mappings["tx"],
            "quickInput.background": mappings["bg"],
            "quickInput.foreground": mappings["tx"],
            "quickInputList.focusBackground": mappings["ui-2"],
            "quickInputList.focusForeground": mappings["tx"],
            "quickInputList.focusIconForeground": mappings["tx"],
            "quickInputTitle.background": mappings["ui-2"],
            "selection.background": mappings["bg-2"],
            "settings.focusedRowBackground": mappings["bg-2"],
            "settings.focusedRowBorder": colorTheme["transparent"],
            "settings.rowHoverBackground": mappings["bg-2"],
            "sideBar.background": mappings["bg-2"],
            "sideBar.border": dark ? mappings["ui"] : mappings["bg-2"],
            "sideBar.foreground": mappings["tx"],
            "sideBarSectionHeader.background": mappings["ui-2"],
            "sideBarSectionHeader.border": mappings["ui-3"],
            "sideBarTitle.foreground": mappings["tx"],
            "statusBar.background": dark ? mappings["ui"] : mappings["bg"],
            "statusBar.border": dark ? mappings["ui"] : mappings["bg-2"],
            "statusBar.debuggingBackground": accent,
            "statusBar.debuggingBorder": mappings["ui"],
            "statusBar.debuggingForeground": tones.paper,
            "statusBar.focusBorder": mappings["ui"],
            "statusBar.foreground": mappings["tx"],
            "statusBar.noFolderBackground": mappings["bg-2"],
            "statusBar.noFolderBorder": mappings["ui"],
            "statusBar.noFolderForeground": mappings["tx"],
            "tab.activeBackground": mappings["bg"],
            "tab.activeBorder": colorTheme["transparent"],
            "tab.activeBorderTop": colorTheme["transparent"],
            "tab.activeForeground": mappings["tx"],
            "tab.border": dark ? mappings["ui-2"] : mappings["ui"],
            "tab.hoverBackground": mappings["bg"],
            "tab.inactiveBackground": mappings["bg-2"],
            "terminal.ansiBlack": tones["base-950"],
            "terminal.ansiBlue": mappings["bl2"],
            "terminal.ansiBrightBlack": tones["base-900"],
            "terminal.ansiBrightBlue": mappings["bl"],
            "terminal.ansiBrightCyan": mappings["cy"],
            "terminal.ansiBrightGreen": mappings["gr"],
            "terminal.ansiBrightMagenta": mappings["ma"],
            "terminal.ansiBrightRed": mappings["re"],
            "terminal.ansiBrightWhite": tones["base-50"],
            "terminal.ansiBrightYellow": mappings["ye"],
            "terminal.ansiCyan": mappings["cy2"],
            "terminal.ansiGreen": mappings["gr2"],
            "terminal.ansiMagenta": mappings["ma2"],
            "terminal.ansiRed": mappings["re2"],
            "terminal.ansiWhite": tones["base-100"],
            "terminal.ansiYellow": mappings["ye2"],
            "terminal.background": mappings["bg"],
            "terminal.border": mappings["ui"],
            "terminal.foreground": mappings["tx"],
            "terminal.selectionBackground": mappings["bg-2"],
            "terminalCursor.foreground": mappings["tx"],
            "titleBar.activeBackground": dark ? mappings["ui"] : mappings["bg"],
            "titleBar.activeForeground": mappings["tx"],
            "titleBar.border": dark ? mappings["ui"] : mappings["bg-2"],
            "titleBar.inactiveBackground": dark ? mappings["ui"] : mappings["bg"],
            "titleBar.inactiveForeground": mappings["tx-3"],
            "toolbar.activeBackground": mappings["bg"],
            "toolbar.hoverBackground": mappings["bg-2"],
            "toolbar.hoverOutline": colorTheme["transparent"],
            "widget.border": mappings["ui"],
            "widget.shadow": dark ? tones["black"] : tones["base-200"],

            // "editorPane.background": test,
            // "editorRuler.foreground": test,
            // "editorStickyScroll.background": test,
            // "editorStickyScroll.border": test,
            // "editorStickyScroll.shadow": test,
            // "editorStickyScrollHover.background": test,

            // "editorUnicodeHighlight.background": test,
            // "editorUnicodeHighlight.border": test,

            // "extensionIcon.preReleaseForeground": test,
            // "extensionIcon.sponsorForeground": test,
            // "extensionIcon.starForeground": test,
            // "extensionIcon.verifiedForeground": test,

            // "inputOption.activeBackground": test,
            // "inputOption.activeBorder": test,
            // "inputOption.activeForeground": test,
            // "inputOption.hoverBackground": test,

            // "notificationCenter.border": test,
            // "notificationCenterHeader.background": test,
            // "notificationCenterHeader.foreground": test,
            // "notificationLink.foreground": test,
            // "notifications.background": test,
            // "notifications.border": test,
            // "notifications.foreground": test,
            // "notificationsErrorIcon.foreground": test,
            // "notificationsInfoIcon.foreground": test,
            // "notificationsWarningIcon.foreground": test,
            // "notificationToast.border": test,
            // "outputView.background": test,
            // "outputViewStickyScroll.background": test,
            // "panel.dropBorder": test,
            // "panelSection.border": test,
            // "panelSection.dropBackground": test,
            // "panelSectionHeader.background": test,
            // "panelSectionHeader.border": test,
            // "panelSectionHeader.foreground": test,
            // "panelTitle.activeBorder": test,
            // "panelTitle.activeForeground": test,
            // "panelTitle.inactiveForeground": test,
            // "peekView.border": test,
            // "peekViewEditor.background": test,
            // "peekViewEditor.matchHighlightBackground": test,
            // "peekViewEditor.matchHighlightBorder": test,
            // "peekViewEditorGutter.background": test,
            // "peekViewEditorStickyScroll.background": test,
            // "peekViewResult.background": test,
            // "peekViewResult.fileForeground": test,
            // "peekViewResult.lineForeground": test,
            // "peekViewResult.matchHighlightBackground": test,
            // "peekViewResult.selectionBackground": test,
            // "peekViewResult.selectionForeground": test,
            // "peekViewTitle.background": test,
            // "peekViewTitleDescription.foreground": test,
            // "peekViewTitleLabel.foreground": test,

            // "symbolIcon.arrayForeground": test,
            // "symbolIcon.booleanForeground": test,
            // "symbolIcon.classForeground": test,
            // "symbolIcon.colorForeground": test,
            // "symbolIcon.constantForeground": test,
            // "symbolIcon.constructorForeground": test,
            // "symbolIcon.enumeratorForeground": test,
            // "symbolIcon.enumeratorMemberForeground": test,
            // "symbolIcon.eventForeground": test,
            // "symbolIcon.fieldForeground": test,
            // "symbolIcon.fileForeground": test,
            // "symbolIcon.folderForeground": test,
            // "symbolIcon.functionForeground": test,
            // "symbolIcon.interfaceForeground": test,
            // "symbolIcon.keyForeground": test,
            // "symbolIcon.keywordForeground": test,
            // "symbolIcon.methodForeground": test,
            // "symbolIcon.moduleForeground": test,
            // "symbolIcon.namespaceForeground": test,
            // "symbolIcon.nullForeground": test,
            // "symbolIcon.numberForeground": test,
            // "symbolIcon.objectForeground": test,
            // "symbolIcon.operatorForeground": test,
            // "symbolIcon.packageForeground": test,
            // "symbolIcon.propertyForeground": test,
            // "symbolIcon.referenceForeground": test,
            // "symbolIcon.snippetForeground": test,
            // "symbolIcon.stringForeground": test,
            // "symbolIcon.structForeground": test,
            // "symbolIcon.textForeground": test,
            // "symbolIcon.typeParameterForeground": test,
            // "symbolIcon.unitForeground": test,
            // "symbolIcon.variableForeground": test,
            // "tab.activeModifiedBorder": test,
            // "tab.dragAndDropBorder": test,
            // "tab.hoverBorder": test,
            // "tab.hoverForeground": test,
            // "tab.inactiveForeground": test,
            // "tab.inactiveModifiedBorder": test,
            // "tab.lastPinnedBorder": test,
            // "tab.unfocusedActiveBackground": test,
            // "tab.unfocusedActiveBorder": test,
            // "tab.unfocusedActiveBorderTop": test,
            // "tab.unfocusedActiveForeground": test,
            // "tab.unfocusedActiveModifiedBorder": test,
            // "tab.unfocusedHoverBackground": test,
            // "tab.unfocusedHoverBorder": test,
            // "tab.unfocusedHoverForeground": test,
            // "tab.unfocusedInactiveBackground": test,
            // "tab.unfocusedInactiveForeground": test,
            // "tab.unfocusedInactiveModifiedBorder": test,
            // "terminal.dropBackground": test,
            // "terminal.findMatchBackground": test,
            // "terminal.findMatchBorder": test,
            // "terminal.findMatchHighlightBackground": test,
            // "terminal.findMatchHighlightBorder": test,
            // "terminal.hoverHighlightBackground": test,
            // "terminal.inactiveSelectionBackground": test,
            // "terminal.selectionForeground": test,
            // "terminal.tab.activeBorder": test,
            // "terminalCommandDecoration.defaultBackground": test,
            // "terminalCommandDecoration.errorBackground": test,
            // "terminalCommandDecoration.successBackground": test,
            // "terminalCursor.background": test,
            // "terminalOverviewRuler.cursorForeground": test,
            // "terminalOverviewRuler.findMatchForeground": test,
            // "terminalStickyScroll.background": test,
            // "terminalStickyScrollHover.background": test,

            // "sideBarSectionHeader.foreground": test,

            // "actionBar.toggledBackground": test,
            // "activityBar.dropBorder": test,
            // "activityBarTop.dropBorder": test,
            // "charts.blue": test,
            // "charts.foreground": test,
            // "charts.green": test,
            // "charts.lines": test,
            // "charts.orange": test,
            // "charts.purple": test,
            // "charts.red": test,
            // "charts.yellow": test,
            // "chat.avatarBackground": test,
            // "chat.avatarForeground": test,
            // "chat.requestBackground": test,
            // "chat.requestBorder": test,
            // "chat.slashCommandBackground": test,
            // "chat.slashCommandForeground": test,
            // "checkbox.background": test,
            // "checkbox.border": test,
            // "checkbox.foreground": test,
            // "checkbox.selectBackground": test,
            // "checkbox.selectBorder": test,
            // "commandCenter.debuggingBackground": test,
            // "commentsView.resolvedIcon": test,
            // "commentsView.unresolvedIcon": test,
            // "contrastActiveBorder": test,
            // "contrastBorder": test,
            // "debugConsole.errorForeground": test,
            // "debugConsole.infoForeground": test,
            // "debugConsole.sourceForeground": test,
            // "debugConsole.warningForeground": test,
            // "debugConsoleInputIcon.foreground": test,
            // "debugExceptionWidget.background": test,
            // "debugExceptionWidget.border": test,
            // "debugIcon.breakpointCurrentStackframeForeground": test,
            // "debugIcon.breakpointDisabledForeground": test,
            // "debugIcon.breakpointForeground": test,
            // "debugIcon.breakpointStackframeForeground": test,
            // "debugIcon.breakpointUnverifiedForeground": test,
            // "debugIcon.continueForeground": test,
            // "debugIcon.disconnectForeground": test,
            // "debugIcon.pauseForeground": test,
            // "debugIcon.restartForeground": test,
            // "debugIcon.startForeground": test,
            // "debugIcon.stepBackForeground": test,
            // "debugIcon.stepIntoForeground": test,
            // "debugIcon.stepOutForeground": test,
            // "debugIcon.stepOverForeground": test,
            // "debugIcon.stopForeground": test,
            // "debugTokenExpression.boolean": test,
            // "debugTokenExpression.error": test,
            // "debugTokenExpression.name": test,
            // "debugTokenExpression.number": test,
            // "debugTokenExpression.string": test,
            // "debugTokenExpression.value": test,
            // "debugToolBar.background": test,
            // "debugToolBar.border": test,
            // "debugView.exceptionLabelBackground": test,
            // "debugView.exceptionLabelForeground": test,
            // "debugView.stateLabelBackground": test,
            // "debugView.stateLabelForeground": test,
            // "debugView.valueChangedHighlight": test,
            // "descriptionForeground": test,
            // "diffEditor.border": test,
            // "diffEditor.diagonalFill": test,
            // "diffEditor.insertedLineBackground": test,
            // "diffEditor.insertedTextBackground": test,
            // "diffEditor.insertedTextBorder": test,
            // "diffEditor.move.border": test,
            // "diffEditor.moveActive.border": test,
            // "diffEditor.removedLineBackground": test,
            // "diffEditor.removedTextBackground": test,
            // "diffEditor.removedTextBorder": test,
            // "diffEditor.unchangedCodeBackground": test,
            // "diffEditor.unchangedRegionBackground": test,
            // "diffEditor.unchangedRegionForeground": test,
            // "diffEditor.unchangedRegionShadow": test,
            // "diffEditorGutter.insertedLineBackground": test,
            // "diffEditorGutter.removedLineBackground": test,
            // "diffEditorOverview.insertedForeground": test,
            // "diffEditorOverview.removedForeground": test,
            // "disabledForeground": test,
            // "editor.findMatchBackground": test,
            // "editor.findMatchBorder": test,
            // "editor.findMatchHighlightBackground": test,
            // "editor.findMatchHighlightBorder": test,
            // "editor.findRangeHighlightBackground": test,
            // "editor.findRangeHighlightBorder": test,
            // "editor.focusedStackFrameHighlightBackground": test,
            // "editor.foldBackground": test,
            // "editor.hoverHighlightBackground": test,
            // "editor.inactiveSelectionBackground": test,
            // "editor.inlineValuesBackground": test,
            // "editor.inlineValuesForeground": test,
            // "editor.lineHighlightBackground": test,
            // "editor.lineHighlightBorder": test,
            // "editor.linkedEditingBackground": test,
            // "editor.rangeHighlightBackground": test,
            // "editor.rangeHighlightBorder": test,
            // "editor.selectionBackground": test,
            // "editor.selectionForeground": test,
            // "editor.selectionHighlightBackground": test,
            // "editor.selectionHighlightBorder": test,
            // "editor.snippetFinalTabstopHighlightBackground": test,
            // "editor.snippetFinalTabstopHighlightBorder": test,
            // "editor.snippetTabstopHighlightBackground": test,
            // "editor.snippetTabstopHighlightBorder": test,
            // "editor.stackFrameHighlightBackground": test,
            // "editor.symbolHighlightBackground": test,
            // "editor.symbolHighlightBorder": test,
            // "editor.wordHighlightBackground": test,
            // "editor.wordHighlightBorder": test,
            // "editor.wordHighlightStrongBackground": test,
            // "editor.wordHighlightStrongBorder": test,
            // "editor.wordHighlightTextBackground": test,
            // "editor.wordHighlightTextBorder": test,
            // "editorCodeLens.foreground": test,
            // "editorCommentsWidget.rangeActiveBackground": test,
            // "editorCommentsWidget.rangeBackground": test,
            // "editorCommentsWidget.replyInputBackground": test,
            // "editorCommentsWidget.resolvedBorder": test,
            // "editorCommentsWidget.unresolvedBorder": test,
            // "editorError.background": test,
            // "editorError.border": test,
            // "editorError.foreground": test,
            // "editorGhostText.background": test,
            // "editorGhostText.border": test,
            // "editorGhostText.foreground": test,
            // "editorGroup.dropBackground": test,
            // "editorGroup.dropIntoPromptBackground": test,
            // "editorGroup.dropIntoPromptBorder": test,
            // "editorGroup.dropIntoPromptForeground": test,
            // "editorGroup.focusedEmptyBorder": test,
            // "editorGutter.addedBackground": test,
            // "editorGutter.background": test,
            // "editorGutter.commentGlyphForeground": test,
            // "editorGutter.commentRangeForeground": test,
            // "editorGutter.commentUnresolvedGlyphForeground": test,
            // "editorGutter.deletedBackground": test,
            // "editorGutter.foldingControlForeground": test,
            // "editorGutter.modifiedBackground": test,
            // "editorHint.border": test,
            // "editorHint.foreground": test,
            // "editorHoverWidget.foreground": test,
            // "editorHoverWidget.highlightForeground": test,
            // "editorHoverWidget.statusBarBackground": test,
            // "editorInfo.background": test,
            // "editorInfo.border": test,
            // "editorInfo.foreground": test,
            // "editorInlayHint.background": test,
            // "editorInlayHint.foreground": test,
            // "editorInlayHint.parameterBackground": test,
            // "editorInlayHint.parameterForeground": test,
            // "editorInlayHint.typeBackground": test,
            // "editorInlayHint.typeForeground": test,
            // "editorLightBulb.foreground": test,
            // "editorLightBulbAi.foreground": test,
            // "editorLightBulbAutoFix.foreground": test,
            // "editorLineNumber.activeForeground": test,
            // "editorLineNumber.dimmedForeground": test,
            // "editorLineNumber.foreground": test,
            // "editorLink.activeForeground": test,
            // "editorMarkerNavigation.background": test,
            // "editorMarkerNavigationError.background": test,
            // "editorMarkerNavigationError.headerBackground": test,
            // "editorMarkerNavigationInfo.background": test,
            // "editorMarkerNavigationInfo.headerBackground": test,
            // "editorMarkerNavigationWarning.background": test,
            // "editorMarkerNavigationWarning.headerBackground": test,
            // "editorOverviewRuler.addedForeground": test,
            // "editorOverviewRuler.background": test,
            // "editorOverviewRuler.border": test,
            // "editorOverviewRuler.bracketMatchForeground": test,
            // "editorOverviewRuler.commentForeground": test,
            // "editorOverviewRuler.commentUnresolvedForeground": test,
            // "editorOverviewRuler.commonContentForeground": test,
            // "editorOverviewRuler.currentContentForeground": test,
            // "editorOverviewRuler.deletedForeground": test,
            // "editorOverviewRuler.errorForeground": test,
            // "editorOverviewRuler.findMatchForeground": test,
            // "editorOverviewRuler.incomingContentForeground": test,
            // "editorOverviewRuler.infoForeground": test,
            // "editorOverviewRuler.inlineChatInserted": test,
            // "editorOverviewRuler.inlineChatRemoved": test,
            // "editorOverviewRuler.modifiedForeground": test,
            // "editorOverviewRuler.rangeHighlightForeground": test,
            // "editorOverviewRuler.selectionHighlightForeground": test,
            // "editorOverviewRuler.warningForeground": test,
            // "editorOverviewRuler.wordHighlightForeground": test,
            // "editorOverviewRuler.wordHighlightStrongForeground": test,
            // "editorOverviewRuler.wordHighlightTextForeground": test,
            // "editorSuggestWidget.border": test,
            // "editorSuggestWidget.focusHighlightForeground": test,
            // "editorSuggestWidget.foreground": test,
            // "editorSuggestWidget.highlightForeground": test,
            // "editorSuggestWidget.selectedBackground": test,
            // "editorSuggestWidget.selectedForeground": test,
            // "editorSuggestWidget.selectedIconForeground": test,
            // "editorSuggestWidgetStatus.foreground": test,
            // "editorUnnecessaryCode.border": test,
            // "editorUnnecessaryCode.opacity": test,
            // "editorWarning.background": test,
            // "editorWarning.border": test,
            // "editorWarning.foreground": test,
            // "editorWatermark.foreground": test,
            // "editorWhitespace.foreground": test,
            // "editorWidget.resizeBorder": test,
            // "errorForeground": test,
            // "inlineChat.background": test,
            // "inlineChat.border": test,
            // "inlineChat.regionHighlight": test,
            // "inlineChat.shadow": test,
            // "inlineChatDiff.inserted": test,
            // "inlineChatDiff.removed": test,
            // "inlineChatInput.background": test,
            // "inlineChatInput.border": test,
            // "inlineChatInput.focusBorder": test,
            // "inlineChatInput.placeholderForeground": test,
            // "inputValidation.errorBackground": test,
            // "inputValidation.errorBorder": test,
            // "inputValidation.errorForeground": test,
            // "inputValidation.infoBackground": test,
            // "inputValidation.infoBorder": test,
            // "inputValidation.infoForeground": test,
            // "inputValidation.warningBackground": test,
            // "inputValidation.warningBorder": test,
            // "inputValidation.warningForeground": test,
            // "interactive.activeCodeBorder": test,
            // "interactive.inactiveCodeBorder": test,
            // "list.activeSelectionIconForeground": test,
            // "list.deemphasizedForeground": test,
            // "list.dropBackground": test,
            // "list.dropBetweenBackground": test,
            // "list.errorForeground": test,
            // "list.filterMatchBackground": test,
            // "list.filterMatchBorder": test,
            // "list.focusAndSelectionOutline": test,
            // "list.focusBackground": test,
            // "list.focusForeground": test,
            // "list.focusHighlightForeground": test,
            // "list.focusOutline": test,
            // "list.highlightForeground": test,
            // "list.hoverForeground": test,
            // "list.inactiveFocusBackground": test,
            // "list.inactiveFocusOutline": test,
            // "list.inactiveSelectionIconForeground": test,
            // "list.invalidItemForeground": test,
            // "list.warningForeground": test,
            // "listFilterWidget.background": test,
            // "listFilterWidget.noMatchesOutline": test,
            // "listFilterWidget.outline": test,
            // "listFilterWidget.shadow": test,
            // "merge.border": test,
            // "merge.commonContentBackground": test,
            // "merge.commonHeaderBackground": test,
            // "merge.currentContentBackground": test,
            // "merge.currentHeaderBackground": test,
            // "merge.incomingContentBackground": test,
            // "merge.incomingHeaderBackground": test,
            // "mergeEditor.change.background": test,
            // "mergeEditor.change.word.background": test,
            // "mergeEditor.changeBase.background": test,
            // "mergeEditor.changeBase.word.background": test,
            // "mergeEditor.conflict.handled.minimapOverViewRuler": test,
            // "mergeEditor.conflict.handledFocused.border": test,
            // "mergeEditor.conflict.handledUnfocused.border": test,
            // "mergeEditor.conflict.input1.background": test,
            // "mergeEditor.conflict.input2.background": test,
            // "mergeEditor.conflict.unhandled.minimapOverViewRuler": test,
            // "mergeEditor.conflict.unhandledFocused.border": test,
            // "mergeEditor.conflict.unhandledUnfocused.border": test,
            // "mergeEditor.conflictingLines.background": test,
            // "minimap.background": test,
            // "minimap.errorHighlight": test,
            // "minimap.findMatchHighlight": test,
            // "minimap.foregroundOpacity": test,
            // "minimap.infoHighlight": test,
            // "minimap.selectionHighlight": test,
            // "minimap.selectionOccurrenceHighlight": test,
            // "minimap.warningHighlight": test,
            // "minimapGutter.addedBackground": test,
            // "minimapGutter.deletedBackground": test,
            // "minimapGutter.modifiedBackground": test,
            // "minimapSlider.activeBackground": test,
            // "minimapSlider.background": test,
            // "minimapSlider.hoverBackground": test,
            // "multiDiffEditor.background": test,
            // "multiDiffEditor.border": test,
            // "multiDiffEditor.headerBackground": test,
            // "notebook.cellBorderColor": test,
            // "notebook.cellEditorBackground": test,
            // "notebook.cellHoverBackground": test,
            // "notebook.cellInsertionIndicator": test,
            // "notebook.cellStatusBarItemHoverBackground": test,
            // "notebook.cellToolbarSeparator": test,
            // "notebook.editorBackground": test,
            // "notebook.focusedCellBackground": test,
            // "notebook.focusedCellBorder": test,
            // "notebook.focusedEditorBorder": test,
            // "notebook.inactiveFocusedCellBorder": test,
            // "notebook.inactiveSelectedCellBorder": test,
            // "notebook.outputContainerBackgroundColor": test,
            // "notebook.outputContainerBorderColor": test,
            // "notebook.selectedCellBackground": test,
            // "notebook.selectedCellBorder": test,
            // "notebook.symbolHighlightBackground": test,
            // "notebookEditorOverviewRuler.runningCellForeground": test,
            // "notebookScrollbarSlider.activeBackground": test,
            // "notebookScrollbarSlider.background": test,
            // "notebookScrollbarSlider.hoverBackground": test,
            // "notebookStatusErrorIcon.foreground": test,
            // "notebookStatusRunningIcon.foreground": test,
            // "notebookStatusSuccessIcon.foreground": test,
            // "ports.iconRunningProcessForeground": test,
            // "problemsErrorIcon.foreground": test,
            // "problemsInfoIcon.foreground": test,
            // "problemsWarningIcon.foreground": test,
            // "profileBadge.background": test,
            // "profileBadge.foreground": test,
            // "progressBar.background": test,
            // "quickInput.list.focusBackground": test,
            // "sash.hoverBorder": test,
            // "scm.historyItemAdditionsForeground": test,
            // "scm.historyItemDeletionsForeground": test,
            // "scm.historyItemSelectedStatisticsBorder": test,
            // "scm.historyItemStatisticsBorder": test,
            // "scrollbar.shadow": test,
            // "scrollbarSlider.activeBackground": test,
            // "scrollbarSlider.background": test,
            // "scrollbarSlider.hoverBackground": test,
            // "search.resultsInfoForeground": test,
            // "searchEditor.findMatchBackground": test,
            // "searchEditor.findMatchBorder": test,
            // "searchEditor.textInputBorder": test,
            // "settings.checkboxBackground": test,
            // "settings.checkboxBorder": test,
            // "settings.checkboxForeground": test,
            // "settings.dropdownBackground": test,
            // "settings.dropdownBorder": test,
            // "settings.dropdownForeground": test,
            // "settings.dropdownListBorder": test,
            // "settings.headerBorder": test,
            // "settings.headerForeground": test,
            // "settings.modifiedItemIndicator": test,
            // "settings.numberInputBackground": test,
            // "settings.numberInputBorder": test,
            // "settings.numberInputForeground": test,
            // "settings.sashBorder": test,
            // "settings.settingsHeaderHoverForeground": test,
            // "settings.textInputBackground": test,
            // "settings.textInputBorder": test,
            // "settings.textInputForeground": test,
            // "sideBar.dropBackground": test,
            // "sideBySideEditor.horizontalBorder": test,
            // "sideBySideEditor.verticalBorder": test,
            // "simpleFindWidget.sashBorder": test,
            // "statusBarItem.activeBackground": test,
            // "statusBarItem.compactHoverBackground": test,
            // "statusBarItem.errorBackground": test,
            // "statusBarItem.errorForeground": test,
            // "statusBarItem.errorHoverBackground": test,
            // "statusBarItem.errorHoverForeground": test,
            // "statusBarItem.focusBorder": test,
            // "statusBarItem.hoverBackground": test,
            // "statusBarItem.hoverForeground": test,
            // "statusBarItem.offlineBackground": test,
            // "statusBarItem.offlineForeground": test,
            // "statusBarItem.offlineHoverBackground": test,
            // "statusBarItem.offlineHoverForeground": test,
            // "statusBarItem.prominentBackground": test,
            // "statusBarItem.prominentForeground": test,
            // "statusBarItem.prominentHoverBackground": test,
            // "statusBarItem.prominentHoverForeground": test,
            // "statusBarItem.remoteBackground": test,
            // "statusBarItem.remoteForeground": test,
            // "statusBarItem.remoteHoverBackground": test,
            // "statusBarItem.remoteHoverForeground": test,
            // "statusBarItem.warningBackground": test,
            // "statusBarItem.warningForeground": test,
            // "statusBarItem.warningHoverBackground": test,
            // "statusBarItem.warningHoverForeground": test,
            // "testing.coverCountBadgeBackground": test,
            // "testing.coverCountBadgeForeground": test,
            // "testing.coveredBackground": test,
            // "testing.coveredBorder": test,
            // "testing.coveredGutterBackground": test,
            // "testing.iconErrored": test,
            // "testing.iconFailed": test,
            // "testing.iconPassed": test,
            // "testing.iconQueued": test,
            // "testing.iconSkipped": test,
            // "testing.iconUnset": test,
            // "testing.message.error.decorationForeground": test,
            // "testing.message.error.lineBackground": test,
            // "testing.message.info.decorationForeground": test,
            // "testing.message.info.lineBackground": test,
            // "testing.messagePeekBorder": test,
            // "testing.messagePeekHeaderBackground": test,
            // "testing.peekBorder": test,
            // "testing.peekHeaderBackground": test,
            // "testing.runAction": test,
            // "testing.uncoveredBackground": test,
            // "testing.uncoveredBorder": test,
            // "testing.uncoveredBranchBackground": test,
            // "testing.uncoveredGutterBackground": test,
            // "textBlockQuote.background": test,
            // "textBlockQuote.border": test,
            // "textCodeBlock.background": test,
            // "textLink.activeForeground": test,
            // "textLink.foreground": test,
            // "textPreformat.background": test,
            // "textPreformat.foreground": test,
            // "textSeparator.foreground": test,
            // "tree.inactiveIndentGuidesStroke": test,
            // "tree.indentGuidesStroke": test,
            // "tree.tableColumnsBorder": test,
            // "tree.tableOddRowsBackground": test,
            // "walkThrough.embeddedEditorBackground": test,
            // "walkthrough.stepTitle.foreground": test,
            // "welcomePage.background": test,
            // "welcomePage.progress.background": test,
            // "welcomePage.progress.foreground": test,
            // "welcomePage.tileBackground": test,
            // "welcomePage.tileBorder": test,
            // "welcomePage.tileHoverBackground": test,
            // "window.activeBorder": test,
            // "window.inactiveBorder": test,
        },
        tokenColors: [
            { scope: ["strong", "markup.bold", "markup.heading"], settings: { fontStyle: "bold" } },
            { scope: ["emphasis, markup.italic"], settings: { fontStyle: "italic" } },
            { scope: ["markup.underline"], settings: { fontStyle: "underline" } },
            { scope: ["markup.strikethrough"], settings: { fontStyle: "strikethrough" } },
            { scope: ["markup.inserted"], settings: { foreground: mappings.gr } },
            { scope: ["markup.deleted"], settings: { foreground: mappings.re } },
            { scope: ["markup.changed"], settings: { foreground: mappings.ye } },
            {
                scope: ["comment", "comment.block", "comment.block.documentation", "comment.line"],
                settings: {
                    foreground: mappings["tx-3"],
                },
            },
            {
                scope: [
                    "constant",
                    "constant.character",
                    "constant.character.escape",
                    "constant.other",
                    "constant.regexp",
                    "constant.rgb-value",
                ],
                settings: {
                    foreground: mappings["ye"],
                },
            },
            {
                scope: [
                    "constant.numeric",
                    "constant.numeric.integer",
                    "constant.numeric.float",
                    "constant.numeric.hex",
                    "constant.numeric.octal",
                ],
                settings: {
                    foreground: mappings["pu"],
                },
            },
            {
                scope: [
                    "entity",
                    "entity.name",
                    "entity.name.class",
                    "entity.name.function",
                    "entity.name.method",
                    "entity.name.section",
                    "entity.name.selector",
                    "entity.name.tag",
                    "entity.name.type",
                    "entity.other",
                    "entity.other.attribute-name",
                    "entity.other.inherited-class",
                    "punctuation.definition.heading",
                ],
                settings: {
                    foreground: mappings["or"],
                },
            },
            {
                scope: ["invalid", "invalid.deprecated", "invalid.illegal"],
                settings: {
                    foreground: mappings["re"],
                },
            },
            {
                scope: ["keyword", "keyword.control", "keyword.other", "string.json"],
                settings: {
                    foreground: mappings["gr"],
                },
            },
            {
                scope: [
                    "keyword.operator",
                    "keyword.operator.new",
                    "keyword.operator.assignment",
                    "keyword.operator.arithmetic",
                    "keyword.operator.logical",
                ],
                settings: {
                    foreground: mappings["tx-2"],
                },
            },
            {
                scope: [
                    "meta",
                    "meta.block",
                    "meta.cast",
                    "meta.class",
                    "meta.function",
                    "meta.function-call",
                    "meta.preprocessor",
                    "meta.return-type",
                    "meta.selector",
                    "meta.tag",
                    "meta.type.annotation",
                    "meta.type",
                ],
                settings: {
                    foreground: mappings["ma"],
                },
            },
            {
                scope: [
                    "punctuation.definition.string.begin",
                    "punctuation.definition.string.end",
                    "punctuation.separator",
                    "punctuation.separator.continuation",
                    "punctuation.terminator",
                ],
                settings: {
                    foreground: mappings["tx-2"],
                },
            },
            {
                scope: ["storage", "storage.modifier", "storage.type"],
                settings: {
                    foreground: mappings["gr"],
                },
            },
            {
                scope: [
                    "string",
                    "string.interpolated",
                    "string.other",
                    "string.quoted",
                    "string.quoted.double",
                    "string.quoted.other",
                    "string.quoted.single",
                    "string.quoted.triple",
                    "string.regexp",
                    "string.unquoted",
                ],
                settings: {
                    foreground: mappings["cy"],
                },
            },
            {
                scope: [
                    "support",
                    "support.class",
                    "support.constant",
                    "support.function",
                    "support.other",
                    "support.type",
                    "support.type.property-name",
                    "support.variable",
                ],
                settings: {
                    foreground: mappings["ye"],
                },
            },
            {
                scope: [
                    "variable",
                    "variable.language",
                    "variable.name",
                    "variable.other",
                    "variable.other.readwrite",
                    "variable.parameter",
                ],
                settings: {
                    foreground: mappings["bl"],
                },
            },
        ],
        semanticTokenColors: {
            newOperator: mappings["gr"],
            stringLiteral: mappings["cy"],
            customLiteral: mappings["tx"],
            numberLiteral: mappings["pu"],
        },
    };
};

console.log(generateTerminal("Dark"));
console.log(generateTerminal("Light"));
